sudo: required
language: python
services:
  - docker
python:
  - '3.6'
before_script:
  - docker-compose build
script:
  - docker-compose run --rm web bash -c "flake8 . &&
                                         python wait_for_postgres.py &&
                                         python manage.py test"

after_success:
- if [ "$TRAVIS_BRANCH" != "master" ]; then docker login --username=_ --password="$HEROKU_AUTH_TOKEN"
  registry.heroku.com; docker tag web registry.heroku.com/ramble-prod/web; docker
  push registry.heroku.com/ramble-prod/web; fi
notifications:
  email: false
cache:
  pip: true
env:
  global:
  - secure: dm7WD7fEriCkQt3751G3thxFbJtVUeh4UaV55lvtQQz6IGYrxHpvutZpcrpH18vOTJYRJfgio2aiOi77Adt0Oc+RRN1FHcMbvgAoem5ecm98AZqinwKS4oWTX/KueWBSokM9XS3Qs0vKzwEpCJLQPgZ0OlLPrjL+gREQ0x5VsqIl+fBUNj9NuNDRk7o607bi8h9jr3BGAlSCgK5v0WdIynqiHOsqmXVAiUO1vKdeSzgo1FpJBoIsQ/rqE0j83bajiA4sYc2uNDBQoSKxdhTp2ztEEd0SyxXt52BBS5ShWZzboidvM8h5ampVY8GbxPoS0axQFwBiywmYVLck6P5g0Bl1402HL38X8eYQMMX3Z8FAq/ymUE338YOkD0mqeF/aSyQTmr4CwCwAe/8h43dPPUIssDE3OwFF4MXkE4Trx7dgH3hyAhaeDS62JomBUta5FOcgJKmQPzbKBwMohQUUKYZq0P3n3XFegaeSHIgYmHSdRXh6MYrcRMsPyPhYsIg2snWw9PnOVwPbi5Gl9teoBn9G6zC3YZD1TVkjBV88g08fMgweryIhbk+85O9whMKR5ChVIHRZDgZH2VIWvu19D65M1IhLkibY21dS+ppLlLyjx+XqmlETxtp/xP6H5vkSMjpVDFX8XYBu8fPHcuNkjtVGAf6nB3ew7UUo7BjAFQ0=
